// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDfSMfqkcZBOm-BT7EUslEgu_sCeGIvm4',
    appId: '1:476164323792:web:4d7287a0ae5942963261d5',
    messagingSenderId: '476164323792',
    projectId: 'ghost-coun',
    authDomain: 'ghost-coun.firebaseapp.com',
    storageBucket: 'ghost-coun.firebasestorage.app',
    measurementId: 'G-1WESDNZCMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtA95QJwC6DA_fKsQuKb1I4Qc4bqov7fI',
    appId: '1:476164323792:android:007c3cc24f5e95373261d5',
    messagingSenderId: '476164323792',
    projectId: 'ghost-coun',
    storageBucket: 'ghost-coun.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4LZ9HOBjRJgRl11fe8TF8ih-p_3eUaDI',
    appId: '1:476164323792:ios:600e317164f1d7eb3261d5',
    messagingSenderId: '476164323792',
    projectId: 'ghost-coun',
    storageBucket: 'ghost-coun.firebasestorage.app',
    iosBundleId: 'com.sazid.ghostCounter',
  );
}
